name: Notificación a Microsoft Teams

# Define los eventos que activarán la acción
on:
  push:         # Activará la notificación en cada push a cualquier rama
    branches:   # Puedes especificar una rama, como main
      - main
  pull_request: # Activará la notificación para los eventos de PR (open, synchronize, close)

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Notificar en Microsoft Teams
        uses: rafaelcalleja/teams-notification-action@v1
        with:
          webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: |
            GitHub Notification: ${{
              github.event_name == 'pull_request' && github.event.action == 'opened' 
                && 'New Pull Request Opened' || 'Code Updated on Main'
            }}
          message: |
            ${{ github.event_name == 'pull_request' && github.event.action == 'opened' 
              && format('Pull request from {} to main branch.', github.actor)
              || format('Push by {}: {}', github.actor, github.sha)
            }}
